ChibiOS/HAL: I2C Driver
I2C Driver
HAL » Normal Drivers
Generic I2C Driver.
Detailed Description
Generic I2C Driver.
This module implements a generic I2C (Inter-Integrated Circuit) driver.
Precondition
In order to use the I2C driver the HAL_USE_I2C option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
The driver is not thread safe for performance reasons, if you need to access the I2C bus from multiple threads then use the i2cAcquireBus() and i2cReleaseBus() APIs in order to gain exclusive access.
Macros
#define I2C_USE_MUTUAL_EXCLUSION TRUE
Enables the mutual exclusion APIs on the I2C bus.
#define _i2c_wakeup_isr(i2cp)
Wakes up the waiting thread notifying no errors.
#define _i2c_wakeup_error_isr(i2cp)
Wakes up the waiting thread notifying errors.
#define i2cMasterTransmit(i2cp, addr, txbuf, txbytes, rxbuf, rxbytes)
Wrap i2cMasterTransmitTimeout function with TIME_INFINITE timeout.
#define i2cMasterReceive(i2cp, addr, rxbuf, rxbytes) (i2cMasterReceiveTimeout(i2cp, addr, rxbuf, rxbytes, TIME_INFINITE))
Wrap i2cMasterReceiveTimeout function with TIME_INFINITE timeout.
#define i2c_lld_get_errors(i2cp) ((i2cp)->errors)
Get errors from I2C driver.
I2C bus error conditions
#define I2C_NO_ERROR 0x00
No error.
#define I2C_BUS_ERROR 0x01
Bus Error.
#define I2C_ARBITRATION_LOST 0x02
Arbitration Lost.
#define I2C_ACK_FAILURE 0x04
Acknowledge Failure.
#define I2C_OVERRUN 0x08
Overrun/Underrun.
#define I2C_PEC_ERROR 0x10
PEC Error in reception.
#define I2C_TIMEOUT 0x20
Hardware timeout.
#define I2C_SMB_ALERT 0x40
SMBus Alert.
PLATFORM configuration options
#define PLATFORM_I2C_USE_I2C1 FALSE
I2C1 driver enable switch.
Typedefs
typedef uint16_t i2caddr_t
Type representing an I2C address.
typedef uint32_t i2cflags_t
Type of I2C Driver condition flags.
typedef struct hal_i2c_config I2CConfig
Type of a structure representing an I2C configuration.
typedef struct hal_i2c_driver I2CDriver
Type of a structure representing an I2C driver.
Data Structures
struct hal_i2c_config
I2C driver configuration structure.
struct hal_i2c_driver
Structure representing an I2C driver.
Functions
void i2cInit (void)
I2C Driver initialization.
void i2cObjectInit (I2CDriver *i2cp)
Initializes the standard part of a I2CDriver structure.
msg_t i2cStart (I2CDriver *i2cp, const I2CConfig *config)
Configures and activates the I2C peripheral.
void i2cStop (I2CDriver *i2cp)
Deactivates the I2C peripheral.
i2cflags_t i2cGetErrors (I2CDriver *i2cp)
Returns the errors mask associated to the previous operation.
msg_t i2cMasterTransmitTimeout (I2CDriver *i2cp, i2caddr_t addr, const uint8_t *txbuf, size_t txbytes, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Sends data via the I2C bus.
msg_t i2cMasterReceiveTimeout (I2CDriver *i2cp, i2caddr_t addr, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data from the I2C bus.
void i2cAcquireBus (I2CDriver *i2cp)
Gains exclusive access to the I2C bus.
void i2cReleaseBus (I2CDriver *i2cp)
Releases exclusive access to the I2C bus.
void i2c_lld_init (void)
Low level I2C driver initialization.
void i2c_lld_start (I2CDriver *i2cp)
Configures and activates the I2C peripheral.
void i2c_lld_stop (I2CDriver *i2cp)
Deactivates the I2C peripheral.
msg_t i2c_lld_master_receive_timeout (I2CDriver *i2cp, i2caddr_t addr, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data via the I2C bus as master.
msg_t i2c_lld_master_transmit_timeout (I2CDriver *i2cp, i2caddr_t addr, const uint8_t *txbuf, size_t txbytes, uint8_t *rxbuf, size_t rxbytes, sysinterval_t timeout)
Transmits data via the I2C bus as master.
Enumerations
enum i2cstate_t {
I2C_UNINIT = 0, I2C_STOP = 1, I2C_READY = 2, I2C_ACTIVE_TX = 3,
I2C_ACTIVE_RX = 4, I2C_LOCKED = 5
}
Driver state machine possible states.
Variables
I2CDriver I2CD1
I2C1 driver identifier.
Macro Definition Documentation
I2C_NO_ERROR
#define I2C_NO_ERROR 0x00
No error.
Definition at line 43 of file hal_i2c.h.
I2C_BUS_ERROR
#define I2C_BUS_ERROR 0x01
Bus Error.
Definition at line 44 of file hal_i2c.h.
I2C_ARBITRATION_LOST
#define I2C_ARBITRATION_LOST 0x02
Arbitration Lost.
Definition at line 45 of file hal_i2c.h.
I2C_ACK_FAILURE
#define I2C_ACK_FAILURE 0x04
Acknowledge Failure.
Definition at line 46 of file hal_i2c.h.
I2C_OVERRUN
#define I2C_OVERRUN 0x08
Overrun/Underrun.
Definition at line 47 of file hal_i2c.h.
I2C_PEC_ERROR
#define I2C_PEC_ERROR 0x10
PEC Error in reception.
Definition at line 48 of file hal_i2c.h.
I2C_TIMEOUT
#define I2C_TIMEOUT 0x20
Hardware timeout.
Definition at line 51 of file hal_i2c.h.
I2C_SMB_ALERT
#define I2C_SMB_ALERT 0x40
SMBus Alert.
Definition at line 52 of file hal_i2c.h.
I2C_USE_MUTUAL_EXCLUSION
#define I2C_USE_MUTUAL_EXCLUSION TRUE
Enables the mutual exclusion APIs on the I2C bus.
Definition at line 63 of file hal_i2c.h.
_i2c_wakeup_isr
#define _i2c_wakeup_isr (i2cp)
Value:
do {                                          \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(i2cp)->thread, MSG_OK);                               \
  osalSysUnlockFromISR();                                                   \
} while (0)
Wakes up the waiting thread notifying no errors.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Not an API, this function is for internal use only.
Definition at line 99 of file hal_i2c.h.
_i2c_wakeup_error_isr
#define _i2c_wakeup_error_isr (i2cp)
Value:
do {                                    \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(i2cp)->thread, MSG_RESET);                            \
  osalSysUnlockFromISR();                                                   \
} while (0)
Wakes up the waiting thread notifying errors.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Not an API, this function is for internal use only.
Definition at line 112 of file hal_i2c.h.
i2cMasterTransmit
#define i2cMasterTransmit (i2cp, addr, txbuf, txbytes, rxbuf, rxbytes)
Value:
(i2cMasterTransmitTimeout(i2cp, addr, txbuf, txbytes, rxbuf, rxbytes,     \
                            TIME_INFINITE))
Wrap i2cMasterTransmitTimeout function with TIME_INFINITE timeout.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 122 of file hal_i2c.h.
i2cMasterReceive
#define i2cMasterReceive (i2cp, addr, rxbuf, rxbytes) (i2cMasterReceiveTimeout(i2cp, addr, rxbuf, rxbytes, TIME_INFINITE))
Wrap i2cMasterReceiveTimeout function with TIME_INFINITE timeout.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 130 of file hal_i2c.h.
PLATFORM_I2C_USE_I2C1
#define PLATFORM_I2C_USE_I2C1 FALSE
I2C1 driver enable switch.
If set to TRUE the support for I2C1 is included.
Note
The default is FALSE.
Definition at line 48 of file hal_i2c_lld.h.
i2c_lld_get_errors
#define i2c_lld_get_errors (i2cp) ((i2cp)->errors)
Get errors from I2C driver.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Not an API, this function is for internal use only.
Definition at line 126 of file hal_i2c_lld.h.
Referenced by i2cGetErrors().
Typedef Documentation
i2caddr_t
typedef uint16_t i2caddr_t
Type representing an I2C address.
Definition at line 63 of file hal_i2c_lld.h.
i2cflags_t
typedef uint32_t i2cflags_t
Type of I2C Driver condition flags.
Definition at line 68 of file hal_i2c_lld.h.
I2CConfig
typedef struct hal_i2c_config I2CConfig
Type of a structure representing an I2C configuration.
Definition at line 83 of file hal_i2c_lld.h.
I2CDriver
typedef struct hal_i2c_driver I2CDriver
Type of a structure representing an I2C driver.
Definition at line 88 of file hal_i2c_lld.h.
Enumeration Type Documentation
i2cstate_t
enum i2cstate_t
Driver state machine possible states.
Enumerator
I2C_UNINIT
Not initialized.
I2C_STOP
Stopped.
I2C_READY
Ready.
I2C_ACTIVE_TX
Transmitting.
I2C_ACTIVE_RX
Receiving.
I2C_LOCKED
Bus locked.
Definition at line 77 of file hal_i2c.h.
Function Documentation
i2cInit()
void i2cInit (void)
I2C Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 59 of file hal_i2c.c.
References i2c_lld_init().
Referenced by halInit().
i2cObjectInit()
void i2cObjectInit (I2CDriver * i2cp)
Initializes the standard part of a I2CDriver structure.
Parameters
[out] i2cp pointer to the I2CDriver object
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 71 of file hal_i2c.c.
References hal_i2c_driver::config, I2C_STOP, osalMutexObjectInit(), and hal_i2c_driver::state.
Referenced by i2c_lld_init().
i2cStart()
msg_t i2cStart (I2CDriver * i2cp, const I2CConfig * config)
Configures and activates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] config pointer to the I2CConfig object
Returns
The operation status.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 94 of file hal_i2c.c.
References hal_i2c_driver::config, i2c_lld_start(), I2C_LOCKED, I2C_READY, I2C_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), and hal_i2c_driver::state.
i2cStop()
void i2cStop (I2CDriver * i2cp)
Deactivates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 130 of file hal_i2c.c.
References hal_i2c_driver::config, i2c_lld_stop(), I2C_LOCKED, I2C_READY, I2C_STOP, osalDbgAssert, osalDbgCheck, osalSysLock(), osalSysUnlock(), and hal_i2c_driver::state.
i2cGetErrors()
i2cflags_t i2cGetErrors (I2CDriver * i2cp)
Returns the errors mask associated to the previous operation.
Parameters
[in] i2cp pointer to the I2CDriver object
Returns
The errors mask.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 154 of file hal_i2c.c.
References i2c_lld_get_errors, and osalDbgCheck.
i2cMasterTransmitTimeout()
msg_t i2cMasterTransmitTimeout (I2CDriver * i2cp, i2caddr_t addr, const uint8_t * txbuf, size_t txbytes, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Sends data via the I2C bus.
Function designed to realize "read-through-write" transfer paradigm. If you want transmit data without any further read, than set rxbytes field to 0.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address (7 bits) without R/W bit
[in] txbuf pointer to transmit buffer
[in] txbytes number of bytes to be transmitted
[out] rxbuf pointer to receive buffer
[in] rxbytes number of bytes to be received, set it to 0 if you want transmit only
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 187 of file hal_i2c.c.
References osalDbgCheck.
i2cMasterReceiveTimeout()
msg_t i2cMasterReceiveTimeout (I2CDriver * i2cp, i2caddr_t addr, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data from the I2C bus.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address (7 bits) without R/W bit
[out] rxbuf pointer to receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 238 of file hal_i2c.c.
References osalDbgCheck.
i2cAcquireBus()
void i2cAcquireBus (I2CDriver * i2cp)
Gains exclusive access to the I2C bus.
This function tries to gain ownership to the I2C bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option I2C_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 278 of file hal_i2c.c.
References osalDbgCheck, and osalMutexLock().
i2cReleaseBus()
void i2cReleaseBus (I2CDriver * i2cp)
Releases exclusive access to the I2C bus.
Precondition
In order to use this function the option I2C_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 294 of file hal_i2c.c.
References osalDbgCheck, and osalMutexUnlock().
i2c_lld_init()
void i2c_lld_init (void)
Low level I2C driver initialization.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 65 of file hal_i2c_lld.c.
References i2cObjectInit().
Referenced by i2cInit().
i2c_lld_start()
void i2c_lld_start (I2CDriver * i2cp)
Configures and activates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Not an API, this function is for internal use only.
Definition at line 79 of file hal_i2c_lld.c.
References I2C_STOP, and hal_i2c_driver::state.
Referenced by i2cStart().
i2c_lld_stop()
void i2c_lld_stop (I2CDriver * i2cp)
Deactivates the I2C peripheral.
Parameters
[in] i2cp pointer to the I2CDriver object
Function Class:^^Not an API, this function is for internal use only.
Definition at line 99 of file hal_i2c_lld.c.
References I2C_STOP, and hal_i2c_driver::state.
Referenced by i2cStop().
i2c_lld_master_receive_timeout()
msg_t i2c_lld_master_receive_timeout (I2CDriver * i2cp, i2caddr_t addr, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Receives data via the I2C bus as master.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
[out] rxbuf pointer to the receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end. After a timeout the driver must be stopped and restarted because the bus is in an uncertain state.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 133 of file hal_i2c_lld.c.
i2c_lld_master_transmit_timeout()
msg_t i2c_lld_master_transmit_timeout (I2CDriver * i2cp, i2caddr_t addr, const uint8_t * txbuf, size_t txbytes, uint8_t * rxbuf, size_t rxbytes, sysinterval_t timeout)
Transmits data via the I2C bus as master.
Parameters
[in] i2cp pointer to the I2CDriver object
[in] addr slave device address
[in] txbuf pointer to the transmit buffer
[in] txbytes number of bytes to be transmitted
[out] rxbuf pointer to the receive buffer
[in] rxbytes number of bytes to be received
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
MSG_OK if the function succeeded.
MSG_RESET if one or more I2C errors occurred, the errors can be retrieved using i2cGetErrors().
MSG_TIMEOUT if a timeout occurred before operation end. After a timeout the driver must be stopped and restarted because the bus is in an uncertain state.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 169 of file hal_i2c_lld.c.
Variable Documentation
I2CD1
I2CDriver I2CD1
I2C1 driver identifier.
Definition at line 41 of file hal_i2c_lld.c.