ChibiOS/HAL: OSAL
OSAL
HAL
Operating System Abstraction Layer.
Detailed Description
Operating System Abstraction Layer.
The OSAL
The OSAL is the link between ChibiOS/HAL and services provided by operating systems like:
Critical Zones handling.
Interrupts handling.
Runtime Errors management.
Inter-task synchronization.
Task-ISR synchronization.
Time management.
Events.
ChibiOS/HAL is designed to tightly integrate with the underlying RTOS in order to provide the best experience to developers and minimize integration issues.
This section describes the API that OSALs are expected to expose to the HAL.
RTOS Requirements
The OSAL API closely resembles the ChibiOS/RT API, for obvious reasons, however an OSAL module can be implemented for any reasonably complete RTOS or even a RTOS-less bare metal machine, if required.
In order to be able to support an HAL an RTOS should support the following minimal set of features:
Task-level critical zones API.
ISR-level critical zones API, only required on those CPU architectures supporting preemptable ISRs like Cortex-Mx cores.
Ability to invoke API functions from inside a task critical zone. Functions that are required to support this feature are marked with an "I" or "S" letter at the end of the name.
Ability to invoke API functions from inside an ISR critical zone. Functions that are required to support this feature are marked with an "I" letter at the end of the name.
Tasks Queues or Counting Semaphores with Timeout capability.
Ability to suspend a task and wakeup it from ISR with Timeout capability.
Event flags, the mechanism can be simulated using callbacks in case the RTOS does not support it.
Mutual Exclusion mechanism like Semaphores or Mutexes.
All the above requirements can be satisfied even on naked HW with a very think SW layer. In case that the HAL is required to work without an RTOS.
Supported RTOSes
The RTOSes supported out of the box are:
ChibiOS/RT
ChibiOS/NIL
Implementations have also been successfully created on RTOSes not belonging to the ChibiOS products family but are not supported as a core feature of ChibiOS/HAL.
Macros
#define OSAL_DBG_ENABLE_ASSERTS FALSE
Enables OSAL assertions.
#define OSAL_DBG_ENABLE_CHECKS FALSE
Enables OSAL functions parameters checks.
Common constants
#define FALSE 0
#define TRUE 1
#define OSAL_SUCCESS false
#define OSAL_FAILED true
Messages
#define MSG_OK (msg_t)0
#define MSG_TIMEOUT (msg_t)-1
#define MSG_RESET (msg_t)-2
Special time constants
#define TIME_IMMEDIATE ((sysinterval_t)0)
#define TIME_INFINITE ((sysinterval_t)-1)
Systick modes.
#define OSAL_ST_MODE_NONE 0
#define OSAL_ST_MODE_PERIODIC 1
#define OSAL_ST_MODE_FREERUNNING 2
Systick parameters.
#define OSAL_ST_RESOLUTION 32
Size in bits of the systick_t type.
#define OSAL_ST_FREQUENCY 1000
Required systick frequency or resolution.
#define OSAL_ST_MODE OSAL_ST_MODE_PERIODIC
Systick mode required by the underlying OS.
IRQ-related constants
#define OSAL_IRQ_PRIORITY_LEVELS 16U
Total priority levels.
#define OSAL_IRQ_MAXIMUM_PRIORITY 0U
Highest IRQ priority for HAL drivers.
Debug related macros
#define osalDbgAssert(c, remark)
Condition assertion.
#define osalDbgCheck(c)
Function parameters check.
#define osalDbgCheckClassI()
I-Class state check.
#define osalDbgCheckClassS()
S-Class state check.
IRQ service routines wrappers
#define OSAL_IRQ_IS_VALID_PRIORITY(n) (((n) >= OSAL_IRQ_MAXIMUM_PRIORITY) && ((n) < OSAL_IRQ_PRIORITY_LEVELS))
Priority level verification macro.
#define OSAL_IRQ_PROLOGUE()
IRQ prologue code.
#define OSAL_IRQ_EPILOGUE()
IRQ epilogue code.
#define OSAL_IRQ_HANDLER(id) void id(void)
IRQ handler function declaration.
Time conversion utilities
#define OSAL_S2I(secs) ((sysinterval_t)((time_conv_t)(secs) * (time_conv_t)OSAL_ST_FREQUENCY))
Seconds to time interval.
#define OSAL_MS2I(msecs)
Milliseconds to time interval.
#define OSAL_US2I(usecs)
Microseconds to time interval.
#define OSAL_I2S(interval)
Time interval to seconds.
#define OSAL_I2MS(interval)
Time interval to milliseconds.
#define OSAL_I2US(interval)
Time interval to microseconds.
Time conversion utilities for the realtime counter
#define OSAL_S2RTC(freq, sec) ((freq) * (sec))
Seconds to realtime counter.
#define OSAL_MS2RTC(freq, msec) (rtcnt_t)((((freq) + 999UL) / 1000UL) * (msec))
Milliseconds to realtime counter.
#define OSAL_US2RTC(freq, usec) (rtcnt_t)((((freq) + 999999UL) / 1000000UL) * (usec))
Microseconds to realtime counter.
Sleep macros using absolute time
#define osalThreadSleepSeconds(secs) osalThreadSleep(OSAL_S2I(secs))
Delays the invoking thread for the specified number of seconds.
#define osalThreadSleepMilliseconds(msecs) osalThreadSleep(OSAL_MS2I(msecs))
Delays the invoking thread for the specified number of milliseconds.
#define osalThreadSleepMicroseconds(usecs) osalThreadSleep(OSAL_US2I(usecs))
Delays the invoking thread for the specified number of microseconds.
Typedefs
typedef uint32_t syssts_t
Type of a system status word.
typedef int32_t msg_t
Type of a message.
typedef uint32_t systime_t
Type of system time counter.
typedef uint32_t sysinterval_t
Type of system time interval.
typedef uint64_t time_conv_t
Type of time conversion variable.
typedef uint32_t rtcnt_t
Type of realtime counter.
typedef void * thread_reference_t
Type of a thread reference.
typedef uint32_t eventflags_t
Type of an event flags mask.
typedef struct event_source event_source_t
Type of an event flags object.
typedef void(* eventcallback_t) (event_source_t *esp)
Type of an event source callback.
typedef uint32_t mutex_t
Type of a mutex.
Data Structures
struct event_source
Events source object.
struct threads_queue_t
Type of a thread queue.
Functions
void osalInit (void)
OSAL module initialization.
void osalSysHalt (const char *reason)
System halt with error message.
void osalSysPolledDelayX (rtcnt_t cycles)
Polled delay.
void osalOsTimerHandlerI (void)
System timer handler.
void osalOsRescheduleS (void)
Checks if a reschedule is required and performs it.
systime_t osalOsGetSystemTimeX (void)
Current system time.
void osalThreadSleepS (sysinterval_t time)
Suspends the invoking thread for the specified time.
void osalThreadSleep (sysinterval_t time)
Suspends the invoking thread for the specified time.
msg_t osalThreadSuspendS (thread_reference_t *trp)
Sends the current thread sleeping and sets a reference variable.
msg_t osalThreadSuspendTimeoutS (thread_reference_t *trp, sysinterval_t timeout)
Sends the current thread sleeping and sets a reference variable.
void osalThreadResumeI (thread_reference_t *trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
void osalThreadResumeS (thread_reference_t *trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
msg_t osalThreadEnqueueTimeoutS (threads_queue_t *tqp, sysinterval_t timeout)
Enqueues the caller thread.
void osalThreadDequeueNextI (threads_queue_t *tqp, msg_t msg)
Dequeues and wakes up one thread from the queue, if any.
void osalThreadDequeueAllI (threads_queue_t *tqp, msg_t msg)
Dequeues and wakes up all threads from the queue.
void osalEventBroadcastFlagsI (event_source_t *esp, eventflags_t flags)
Add flags to an event source object.
void osalEventBroadcastFlags (event_source_t *esp, eventflags_t flags)
Add flags to an event source object.
void osalEventSetCallback (event_source_t *esp, eventcallback_t cb, void *param)
Event callback setup.
void osalMutexLock (mutex_t *mp)
Locks the specified mutex.
void osalMutexUnlock (mutex_t *mp)
Unlocks the specified mutex.
static void osalSysDisable (void)
Disables interrupts globally.
static void osalSysEnable (void)
Enables interrupts globally.
static void osalSysLock (void)
Enters a critical zone from thread context.
static void osalSysUnlock (void)
Leaves a critical zone from thread context.
static void osalSysLockFromISR (void)
Enters a critical zone from ISR context.
static void osalSysUnlockFromISR (void)
Leaves a critical zone from ISR context.
static syssts_t osalSysGetStatusAndLockX (void)
Returns the execution status and enters a critical zone.
static void osalSysRestoreStatusX (syssts_t sts)
Restores the specified execution status and leaves a critical zone.
static systime_t osalTimeAddX (systime_t systime, sysinterval_t interval)
Adds an interval to a system time returning a system time.
static sysinterval_t osalTimeDiffX (systime_t start, systime_t end)
Subtracts two system times returning an interval.
static bool osalTimeIsInRangeX (systime_t time, systime_t start, systime_t end)
Checks if the specified time is within the specified time window.
static void osalThreadQueueObjectInit (threads_queue_t *tqp)
Initializes a threads queue object.
static void osalEventObjectInit (event_source_t *esp)
Initializes an event source object.
static void osalMutexObjectInit (mutex_t *mp)
Initializes s mutex_t object.
Variables
const char * osal_halt_msg
Pointer to a halt error message.
const char * osal_halt_msg
Pointer to a halt error message.
Macro Definition Documentation
OSAL_ST_RESOLUTION
#define OSAL_ST_RESOLUTION 32
Size in bits of the systick_t type.
Definition at line 85 of file osal.h.
OSAL_ST_FREQUENCY
#define OSAL_ST_FREQUENCY 1000
Required systick frequency or resolution.
Definition at line 90 of file osal.h.
OSAL_ST_MODE
#define OSAL_ST_MODE OSAL_ST_MODE_PERIODIC
Systick mode required by the underlying OS.
Definition at line 95 of file osal.h.
OSAL_IRQ_PRIORITY_LEVELS
#define OSAL_IRQ_PRIORITY_LEVELS 16U
Total priority levels.
Implementation not mandatory.
Definition at line 106 of file osal.h.
OSAL_IRQ_MAXIMUM_PRIORITY
#define OSAL_IRQ_MAXIMUM_PRIORITY 0U
Highest IRQ priority for HAL drivers.
Implementation not mandatory.
Definition at line 112 of file osal.h.
OSAL_DBG_ENABLE_ASSERTS
#define OSAL_DBG_ENABLE_ASSERTS FALSE
Enables OSAL assertions.
Definition at line 123 of file osal.h.
OSAL_DBG_ENABLE_CHECKS
#define OSAL_DBG_ENABLE_CHECKS FALSE
Enables OSAL functions parameters checks.
Definition at line 130 of file osal.h.
osalDbgAssert
#define osalDbgAssert (c, remark)
Value:
do {                                       \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (OSAL_DBG_ENABLE_ASSERTS != FALSE) {                                   \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      osalSysHalt(__func__);                                                \
    }                                                                       \
  }                                                                         \
} while (false)
Condition assertion.
If the condition check fails then the OSAL panics with a message and halts.
Note
The condition is tested only if the OSAL_ENABLE_ASSERTIONS switch is enabled.
The remark string is not currently used except for putting a comment in the code about the assertion.
Parameters
[in] c the condition to be verified to be true
[in] remark a remark string
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 264 of file osal.h.
Referenced by _usb_ep0out(), adcConvert(), adcStart(), adcStartConversionI(), adcStop(), adcStopConversion(), adcStopConversionI(), canReceiveTimeout(), canSleep(), canStart(), canStop(), canTransmitTimeout(), canTryReceiveI(), canTryTransmitI(), canWakeup(), cryDecryptAES(), cryDecryptAES_CBC(), cryDecryptAES_CFB(), cryDecryptAES_CTR(), cryDecryptAES_ECB(), cryDecryptAES_GCM(), cryDecryptDES(), cryDecryptDES_CBC(), cryDecryptDES_ECB(), cryEncryptAES(), cryEncryptAES_CBC(), cryEncryptAES_CFB(), cryEncryptAES_CTR(), cryEncryptAES_ECB(), cryEncryptAES_GCM(), cryEncryptDES(), cryEncryptDES_CBC(), cryEncryptDES_ECB(), cryHMACSHA256Final(), cryHMACSHA256Init(), cryHMACSHA256Update(), cryHMACSHA512Final(), cryHMACSHA512Init(), cryHMACSHA512Update(), crySHA1Final(), crySHA1Init(), crySHA1Update(), crySHA256Final(), crySHA256Init(), crySHA256Update(), crySHA512Final(), crySHA512Init(), crySHA512Update(), cryStart(), cryStop(), dacPutChannelX(), dacStart(), dacStartConversionI(), dacStop(), dacStopConversion(), dacStopConversionI(), efl_lld_start_erase_all(), efl_lld_start_erase_sector(), eflStart(), eflStop(), flashGetSectorOffset(), flashGetSectorSize(), gptChangeInterval(), gptPolledDelay(), gptStart(), gptStartContinuousI(), gptStartOneShotI(), gptStop(), gptStopTimerI(), i2cStart(), i2cStop(), i2sStart(), i2sStartExchange(), i2sStop(), i2sStopExchange(), ibqPostFullBufferI(), ibqReleaseEmptyBufferS(), icuDisableNotifications(), icuEnableNotifications(), icuStart(), icuStartCapture(), icuStop(), icuStopCapture(), icuWaitCapture(), macPollLinkStatus(), macStart(), macStop(), macWaitReceiveDescriptor(), macWaitTransmitDescriptor(), mfsStart(), mfsStop(), mmc_cmd6_construct(), mmcConnect(), mmcDisconnect(), mmcStart(), mmcStartSequentialRead(), mmcStartSequentialWrite(), mmcStop(), obnotify(), obqPostFullBufferS(), obqReleaseEmptyBufferI(), pwmChangePeriod(), pwmDisableChannel(), pwmDisableChannelNotification(), pwmDisablePeriodicNotification(), pwmEnableChannel(), pwmEnableChannelNotification(), pwmEnablePeriodicNotification(), pwmStart(), pwmStop(), sdc_cmd6_construct(), sdcDisconnect(), sdcErase(), sdcGetAndClearErrors(), sdcRead(), sdcStart(), sdcStop(), sdcWrite(), sdStart(), sdStop(), sduSOFHookI(), sduStart(), sduStop(), sioStart(), sioStartOperation(), sioStop(), sioStopOperation(), sioSynchronizeTXEnd(), snor_get_descriptor(), snorStart(), snorStop(), spi_lld_start(), spi_lld_stop(), stGetAlarm(), stSetAlarm(), stStartAlarm(), trngGenerate(), trngStart(), trngStop(), uartReceiveTimeout(), uartSendFullTimeout(), uartSendTimeout(), uartStart(), uartStartReceive(), uartStartReceiveI(), uartStartSend(), uartStartSendI(), uartStop(), uartStopReceive(), uartStopReceiveI(), uartStopSend(), uartStopSendI(), usbDisableEndpointsI(), usbInitEndpointI(), usbStart(), usbStartReceiveI(), usbStartTransmitI(), usbStop(), wdgReset(), wdgStart(), wdgStop(), wspiStart(), wspiStartCommand(), wspiStartReceive(), wspiStartSend(), wspiStop(), and wspiUnmapFlash().
osalDbgCheck
#define osalDbgCheck (c)
Value:
do {                                                \
  /*lint -save -e506 -e774 [2.1, 14.3] Can be a constant by design.*/       \
  if (OSAL_DBG_ENABLE_CHECKS != FALSE) {                                    \
    if (!(c)) {                                                             \
  /*lint -restore*/                                                         \
      osalSysHalt(__func__);                                                \
    }                                                                       \
  }                                                                         \
} while (false)
Function parameters check.
If the condition check fails then the OSAL panics and halts.
Note
The condition is tested only if the OSAL_ENABLE_CHECKS switch is enabled.
Parameters
[in] c the condition to be verified to be true
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 284 of file osal.h.
Referenced by _mmcsd_get_capacity(), _mmcsd_get_capacity_ext(), _mmcsd_get_slice(), _mmcsd_unpack_csd_mmc(), _mmcsd_unpack_csd_v10(), _mmcsd_unpack_csd_v20(), _mmcsd_unpack_mmc_cid(), _mmcsd_unpack_sdc_cid(), adcAcquireBus(), adcReleaseBus(), adcStart(), adcStartConversionI(), adcStop(), adcStopConversion(), adcStopConversionI(), canReceiveTimeout(), canSleep(), canStart(), canStop(), canTransmitTimeout(), canTryAbortX(), canTryReceiveI(), canTryTransmitI(), canWakeup(), cryDecryptAES(), cryDecryptAES_CBC(), cryDecryptAES_CFB(), cryDecryptAES_CTR(), cryDecryptAES_ECB(), cryDecryptAES_GCM(), cryDecryptDES(), cryDecryptDES_CBC(), cryDecryptDES_ECB(), cryEncryptAES(), cryEncryptAES_CBC(), cryEncryptAES_CFB(), cryEncryptAES_CTR(), cryEncryptAES_ECB(), cryEncryptAES_GCM(), cryEncryptDES(), cryEncryptDES_CBC(), cryEncryptDES_ECB(), cryHMACSHA256Final(), cryHMACSHA256Init(), cryHMACSHA256Update(), cryHMACSHA512Final(), cryHMACSHA512Init(), cryHMACSHA512Update(), cryLoadAESTransientKey(), cryLoadDESTransientKey(), cryLoadHMACTransientKey(), crySHA1Final(), crySHA1Init(), crySHA1Update(), crySHA256Final(), crySHA256Init(), crySHA256Update(), crySHA512Final(), crySHA512Init(), crySHA512Update(), cryStart(), cryStop(), dacAcquireBus(), dacPutChannelX(), dacReleaseBus(), dacStart(), dacStartConversionI(), dacStop(), dacStopConversion(), dacStopConversionI(), efl_lld_start_erase_all(), efl_lld_start_erase_sector(), eflAcquireBus(), eflReleaseBus(), eflStart(), eflStop(), gptChangeInterval(), gptStart(), gptStartContinuousI(), gptStartOneShotI(), gptStop(), gptStopTimerI(), i2cAcquireBus(), i2cGetErrors(), i2cMasterReceiveTimeout(), i2cMasterTransmitTimeout(), i2cReleaseBus(), i2cStart(), i2cStop(), i2sStart(), i2sStartExchange(), i2sStop(), i2sStopExchange(), ibqObjectInit(), ibqPostFullBufferI(), ibqReadTimeout(), icuDisableNotifications(), icuEnableNotifications(), icuStart(), icuStartCapture(), icuStop(), icuStopCapture(), icuWaitCapture(), iq_read(), iqReadTimeout(), macPollLinkStatus(), macReleaseReceiveDescriptor(), macReleaseTransmitDescriptor(), macStart(), macStop(), macWaitReceiveDescriptor(), macWaitTransmitDescriptor(), mfsCommitTransaction(), mfsErase(), mfsEraseRecord(), mfsObjectInit(), mfsPerformGarbageCollection(), mfsReadRecord(), mfsRollbackTransaction(), mfsStart(), mfsStartTransaction(), mfsStop(), mfsWriteRecord(), mmcConnect(), mmcDisconnect(), mmcErase(), mmcGetInfo(), mmcSequentialRead(), mmcSequentialWrite(), mmcStart(), mmcStartSequentialRead(), mmcStartSequentialWrite(), mmcStop(), mmcStopSequentialWrite(), mmcSync(), obqObjectInit(), obqPostFullBufferS(), obqWriteTimeout(), oq_write(), oqWriteTimeout(), osalEventBroadcastFlags(), osalEventBroadcastFlagsI(), osalEventObjectInit(), osalEventSetCallback(), osalMutexLock(), osalMutexObjectInit(), osalMutexUnlock(), osalThreadDequeueNextI(), osalThreadEnqueueTimeoutS(), osalThreadQueueObjectInit(), osalThreadResumeI(), osalThreadResumeS(), osalThreadSuspendS(), osalThreadSuspendTimeoutS(), palReadBus(), palSetBusMode(), palWriteBus(), pwmChangePeriod(), pwmDisableChannel(), pwmDisableChannelNotification(), pwmDisablePeriodicNotification(), pwmEnableChannel(), pwmEnableChannelNotification(), pwmEnablePeriodicNotification(), pwmStart(), pwmStop(), rtcGetAlarm(), rtcGetTime(), rtcSetAlarm(), rtcSetCallback(), rtcSetTime(), sdcDisconnect(), sdcErase(), sdcGetAndClearErrors(), sdcGetInfo(), sdcRead(), sdcStart(), sdcStop(), sdcSync(), sdcWrite(), sdIncomingDataI(), sdRequestDataI(), sdStart(), sdStop(), sduStart(), sduStop(), sioAsyncRead(), sioAsyncWrite(), sioGetAndClearEvents(), sioStart(), sioStartOperation(), sioStop(), sioStopOperation(), sioSynchronizeTXEnd(), snor_get_descriptor(), snorObjectInit(), snorStart(), snorStop(), stBindAlarmN(), stGetAlarmN(), stIsAlarmActiveN(), stSetAlarmN(), stStartAlarmN(), stStopAlarmN(), trngGenerate(), trngStart(), trngStop(), uartAcquireBus(), uartReceiveTimeout(), uartReleaseBus(), uartSendFullTimeout(), uartSendTimeout(), uartStart(), uartStartReceive(), uartStartReceiveI(), uartStartSend(), uartStartSendI(), uartStop(), uartStopReceive(), uartStopReceiveI(), uartStopSend(), uartStopSendI(), usbDisableEndpointsI(), usbInitEndpointI(), usbStallReceiveI(), usbStallTransmitI(), usbStart(), usbStartReceiveI(), usbStartTransmitI(), usbStop(), wdgReset(), wdgStart(), wdgStop(), wspiAcquireBus(), wspiCommand(), wspiMapFlash(), wspiReceive(), wspiReleaseBus(), wspiSend(), wspiStart(), wspiStartCommand(), wspiStartReceive(), wspiStartSend(), wspiStop(), and wspiUnmapFlash().
osalDbgCheckClassI
#define osalDbgCheckClassI ()
I-Class state check.
Note
Implementation is optional.
Definition at line 298 of file osal.h.
Referenced by adcStartConversionI(), adcStopConversionI(), canTryReceiveI(), canTryTransmitI(), dacStartConversionI(), dacStopConversionI(), gptStartContinuousI(), gptStartOneShotI(), gptStopTimerI(), ibqGetEmptyBufferI(), ibqPostFullBufferI(), ibqResetI(), iqGetI(), iqPutI(), iqReadI(), iqResetI(), obqGetFullBufferI(), obqReleaseEmptyBufferI(), obqResetI(), obqTryFlushI(), oqGetI(), oqPutI(), oqResetI(), oqWriteI(), osalOsTimerHandlerI(), sdIncomingDataI(), sdRequestDataI(), uartStartReceiveI(), uartStartSendI(), uartStopReceiveI(), uartStopSendI(), usbDisableEndpointsI(), usbInitEndpointI(), usbStallReceiveI(), usbStallTransmitI(), usbStartReceiveI(), and usbStartTransmitI().
osalDbgCheckClassS
#define osalDbgCheckClassS ()
S-Class state check.
Note
Implementation is optional.
Definition at line 304 of file osal.h.
Referenced by ibqGetFullBufferTimeoutS(), ibqReleaseEmptyBufferS(), obqGetEmptyBufferTimeoutS(), and obqPostFullBufferS().
OSAL_IRQ_IS_VALID_PRIORITY
#define OSAL_IRQ_IS_VALID_PRIORITY (n) (((n) >= OSAL_IRQ_MAXIMUM_PRIORITY) && ((n) < OSAL_IRQ_PRIORITY_LEVELS))
Priority level verification macro.
Definition at line 314 of file osal.h.
OSAL_IRQ_PROLOGUE
#define OSAL_IRQ_PROLOGUE ()
IRQ prologue code.
This macro must be inserted at the start of all IRQ handlers.
Definition at line 321 of file osal.h.
OSAL_IRQ_EPILOGUE
#define OSAL_IRQ_EPILOGUE ()
IRQ epilogue code.
This macro must be inserted at the end of all IRQ handlers.
Definition at line 327 of file osal.h.
OSAL_IRQ_HANDLER
#define OSAL_IRQ_HANDLER (id) void id(void)
IRQ handler function declaration.
This macro hides the details of an ISR function declaration.
Parameters
[in] id a vector name as defined in vectors.s
Definition at line 335 of file osal.h.
OSAL_S2I
#define OSAL_S2I (secs) ((sysinterval_t)((time_conv_t)(secs) * (time_conv_t)OSAL_ST_FREQUENCY))
Seconds to time interval.
Converts from seconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] secs number of seconds
Returns
The number of ticks.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 355 of file osal.h.
OSAL_MS2I
#define OSAL_MS2I (msecs)
Value:
((sysinterval_t)((((time_conv_t)(msecs) *                                 \
                     (time_conv_t)OSAL_ST_FREQUENCY) +                      \
                    (time_conv_t)999) / (time_conv_t)1000))
Milliseconds to time interval.
Converts from milliseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] msecs number of milliseconds
Returns
The number of ticks.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 371 of file osal.h.
OSAL_US2I
#define OSAL_US2I (usecs)
Value:
((sysinterval_t)((((time_conv_t)(usecs) *                                 \
                     (time_conv_t)OSAL_ST_FREQUENCY) +                      \
                    (time_conv_t)999999) / (time_conv_t)1000000))
Microseconds to time interval.
Converts from microseconds to system ticks number.
Note
The result is rounded upward to the next tick boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] usecs number of microseconds
Returns
The number of ticks.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 389 of file osal.h.
OSAL_I2S
#define OSAL_I2S (interval)
Value:
(time_secs_t)(((time_conv_t)(interval) +                                  \
                 (time_conv_t)OSAL_ST_FREQUENCY -                           \
                 (time_conv_t)1) / (time_conv_t)OSAL_ST_FREQUENCY)
Time interval to seconds.
Converts from system ticks number to seconds.
Note
The result is rounded up to the next second boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] interval interval in ticks
Returns
The number of seconds.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 407 of file osal.h.
OSAL_I2MS
#define OSAL_I2MS (interval)
Value:
(time_msecs_t)((((time_conv_t)(interval) * (time_conv_t)1000) +           \
                  (time_conv_t)OSAL_ST_FREQUENCY - (time_conv_t)1) /        \
                 (time_conv_t)OSAL_ST_FREQUENCY)
Time interval to milliseconds.
Converts from system ticks number to milliseconds.
Note
The result is rounded up to the next millisecond boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] interval interval in ticks
Returns
The number of milliseconds.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 425 of file osal.h.
OSAL_I2US
#define OSAL_I2US (interval)
Value:
(time_msecs_t)((((time_conv_t)(interval) * (time_conv_t)1000000) +        \
                  (time_conv_t)OSAL_ST_FREQUENCY - (time_conv_t)1) /        \
                 (time_conv_t)OSAL_ST_FREQUENCY)
Time interval to microseconds.
Converts from system ticks number to microseconds.
Note
The result is rounded up to the next microsecond boundary.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] interval interval in ticks
Returns
The number of microseconds.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 443 of file osal.h.
OSAL_S2RTC
#define OSAL_S2RTC (freq, sec) ((freq) * (sec))
Seconds to realtime counter.
Converts from seconds to realtime counter cycles.
Note
The macro assumes that freq >= 1.
Parameters
[in] freq clock frequency, in Hz, of the realtime counter
[in] sec number of seconds
Returns
The number of cycles.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 464 of file osal.h.
OSAL_MS2RTC
#define OSAL_MS2RTC (freq, msec) (rtcnt_t)((((freq) + 999UL) / 1000UL) * (msec))
Milliseconds to realtime counter.
Converts from milliseconds to realtime counter cycles.
Note
The result is rounded upward to the next millisecond boundary.
The macro assumes that freq >= 1000.
Parameters
[in] freq clock frequency, in Hz, of the realtime counter
[in] msec number of milliseconds
Returns
The number of cycles.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 478 of file osal.h.
OSAL_US2RTC
#define OSAL_US2RTC (freq, usec) (rtcnt_t)((((freq) + 999999UL) / 1000000UL) * (usec))
Microseconds to realtime counter.
Converts from microseconds to realtime counter cycles.
Note
The result is rounded upward to the next microsecond boundary.
The macro assumes that freq >= 1000000.
Parameters
[in] freq clock frequency, in Hz, of the realtime counter
[in] usec number of microseconds
Returns
The number of cycles.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 492 of file osal.h.
osalThreadSleepSeconds
#define osalThreadSleepSeconds (secs) osalThreadSleep(OSAL_S2I(secs))
Delays the invoking thread for the specified number of seconds.
Note
The specified time is rounded up to a value allowed by the real system tick clock.
The maximum specifiable value is implementation dependent.
Parameters
[in] secs time in seconds, must be different from zero
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 509 of file osal.h.
osalThreadSleepMilliseconds
#define osalThreadSleepMilliseconds (msecs) osalThreadSleep(OSAL_MS2I(msecs))
Delays the invoking thread for the specified number of milliseconds.
Note
The specified time is rounded up to a value allowed by the real system tick clock.
The maximum specifiable value is implementation dependent.
Parameters
[in] msecs time in milliseconds, must be different from zero
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 522 of file osal.h.
osalThreadSleepMicroseconds
#define osalThreadSleepMicroseconds (usecs) osalThreadSleep(OSAL_US2I(usecs))
Delays the invoking thread for the specified number of microseconds.
Note
The specified time is rounded up to a value allowed by the real system tick clock.
The maximum specifiable value is implementation dependent.
Parameters
[in] usecs time in microseconds, must be different from zero
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 535 of file osal.h.
Typedef Documentation
syssts_t
typedef uint32_t syssts_t
Type of a system status word.
Definition at line 154 of file osal.h.
msg_t
typedef int32_t msg_t
Type of a message.
Definition at line 159 of file osal.h.
systime_t
typedef uint32_t systime_t
Type of system time counter.
Definition at line 164 of file osal.h.
sysinterval_t
typedef uint32_t sysinterval_t
Type of system time interval.
Definition at line 169 of file osal.h.
time_conv_t
typedef uint64_t time_conv_t
Type of time conversion variable.
Note
This type must have double width than other time types, it is only used internally for conversions.
Definition at line 176 of file osal.h.
rtcnt_t
typedef uint32_t rtcnt_t
Type of realtime counter.
Definition at line 181 of file osal.h.
thread_reference_t
typedef void* thread_reference_t
Type of a thread reference.
Definition at line 186 of file osal.h.
eventflags_t
typedef uint32_t eventflags_t
Type of an event flags mask.
Definition at line 191 of file osal.h.
event_source_t
typedef struct event_source event_source_t
Type of an event flags object.
Note
The content of this structure is not part of the API and should not be relied upon. Implementers may define this structure in an entirely different way.
Retrieval and clearing of the flags are not defined in this API and are implementation-dependent.
Definition at line 201 of file osal.h.
eventcallback_t
typedef void(* eventcallback_t) (event_source_t *esp)
Type of an event source callback.
Note
This type is not part of the OSAL API and is provided exclusively as an example and for convenience.
Definition at line 208 of file osal.h.
mutex_t
typedef uint32_t mutex_t
Type of a mutex.
Note
If the OS does not support mutexes or there is no OS then them mechanism can be simulated.
Definition at line 229 of file osal.h.
Function Documentation
osalInit()
void osalInit (void)
OSAL module initialization.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 63 of file osal.c.
Referenced by halInit().
osalSysHalt()
void osalSysHalt (const char * reason)
System halt with error message.
Parameters
[in] reason the halt message pointer
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 77 of file osal.c.
References osal_halt_msg, and osalSysDisable().
osalSysPolledDelayX()
void osalSysPolledDelayX (rtcnt_t cycles)
Polled delay.
Note
The real delay is always few cycles in excess of the specified value.
Parameters
[in] cycles number of cycles
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 94 of file osal.c.
osalOsTimerHandlerI()
void osalOsTimerHandlerI (void)
System timer handler.
The handler is used for scheduling and Virtual Timers management.
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 105 of file osal.c.
References osalDbgCheckClassI.
osalOsRescheduleS()
void osalOsRescheduleS (void)
Checks if a reschedule is required and performs it.
Note
I-Class functions invoked from thread context must not reschedule by themselves, an explicit reschedule using this function is required in this scenario.
Not implemented in this simplified OSAL.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 119 of file osal.c.
Referenced by canSleep(), canWakeup(), sdStop(), and sduStop().
osalOsGetSystemTimeX()
systime_t osalOsGetSystemTimeX (void)
Current system time.
Returns the number of system ticks since the osalInit() invocation.
Note
The counter can reach its maximum and then restart from zero.
This function can be called from any context but its atomicity is not guaranteed on architectures whose word size is less than systime_t size.
Returns
The system time in ticks.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 136 of file osal.c.
osalThreadSleepS()
void osalThreadSleepS (sysinterval_t time)
Suspends the invoking thread for the specified time.
Parameters
[in] time the delay in system ticks, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 153 of file osal.c.
osalThreadSleep()
void osalThreadSleep (sysinterval_t time)
Suspends the invoking thread for the specified time.
Parameters
[in] time the delay in system ticks, the special values are handled as follow:
TIME_INFINITE is allowed but interpreted as a normal time specification.
TIME_IMMEDIATE this value is not allowed.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 170 of file osal.c.
osalThreadSuspendS()
msg_t osalThreadSuspendS (thread_reference_t * trp)
Sends the current thread sleeping and sets a reference variable.
Note
This function must reschedule, it can only be called from thread context.
Parameters
[in] trp a pointer to a thread reference object
Returns
The wake up message.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 185 of file osal.c.
References osalDbgCheck.
Referenced by adcConvert(), and dacConvert().
osalThreadSuspendTimeoutS()
msg_t osalThreadSuspendTimeoutS (thread_reference_t * trp, sysinterval_t timeout)
Sends the current thread sleeping and sets a reference variable.
Note
This function must reschedule, it can only be called from thread context.
Parameters
[in] trp a pointer to a thread reference object
[in] timeout the timeout in system ticks, the special values are handled as follow:
TIME_INFINITE the thread enters an infinite sleep state.
TIME_IMMEDIATE the thread is not enqueued and the function returns MSG_TIMEOUT as if a timeout occurred.
Returns
The wake up message.
Return values
MSG_TIMEOUT if the operation timed out.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 211 of file osal.c.
References osalDbgCheck.
Referenced by sioSynchronizeTXEnd(), uartReceiveTimeout(), uartSendFullTimeout(), and uartSendTimeout().
osalThreadResumeI()
void osalThreadResumeI (thread_reference_t * trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
Note
This function must not reschedule because it can be called from ISR context.
Parameters
[in] trp a pointer to a thread reference object
[in] msg the message code
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 230 of file osal.c.
References osalDbgCheck.
Referenced by _usb_reset(), _usb_suspend(), sioStopOperation(), usbDisableEndpointsI(), and usbStop().
osalThreadResumeS()
void osalThreadResumeS (thread_reference_t * trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
Note
This function must reschedule, it can only be called from thread context.
Parameters
[in] trp a pointer to a thread reference object
[in] msg the message code
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 247 of file osal.c.
References osalDbgCheck.
osalThreadEnqueueTimeoutS()
msg_t osalThreadEnqueueTimeoutS (threads_queue_t * tqp, sysinterval_t timeout)
Enqueues the caller thread.
The caller thread is enqueued and put to sleep until it is dequeued or the specified timeouts expires.
Parameters
[in] tqp pointer to the threads queue object
[in] timeout the timeout in system ticks, the special values are handled as follow:
TIME_INFINITE the thread enters an infinite sleep state.
TIME_IMMEDIATE the thread is not enqueued and the function returns MSG_TIMEOUT as if a timeout occurred.
Returns
The message from osalQueueWakeupOneI() or osalQueueWakeupAllI() functions.
Return values
MSG_TIMEOUT if the thread has not been dequeued within the specified timeout or if the function has been invoked with TIME_IMMEDIATE as timeout specification.
Function Class:^^This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 277 of file osal.c.
References osalDbgCheck.
Referenced by canReceiveTimeout(), canTransmitTimeout(), iqGetTimeout(), iqReadTimeout(), oqPutTimeout(), oqWriteTimeout(), palWaitLineTimeoutS(), and palWaitPadTimeoutS().
osalThreadDequeueNextI()
void osalThreadDequeueNextI (threads_queue_t * tqp, msg_t msg)
Dequeues and wakes up one thread from the queue, if any.
Parameters
[in] tqp pointer to the threads queue object
[in] msg the message code
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 294 of file osal.c.
References osalDbgCheck.
Referenced by ibqPostFullBufferI(), iqPutI(), obqReleaseEmptyBufferI(), and oqGetI().
osalThreadDequeueAllI()
void osalThreadDequeueAllI (threads_queue_t * tqp, msg_t msg)
Dequeues and wakes up all threads from the queue.
Parameters
[in] tqp pointer to the threads queue object
[in] msg the message code
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 309 of file osal.c.
Referenced by canStop(), ibqResetI(), iqResetI(), obqResetI(), and oqResetI().
osalEventBroadcastFlagsI()
void osalEventBroadcastFlagsI (event_source_t * esp, eventflags_t flags)
Add flags to an event source object.
Parameters
[in] esp pointer to the event flags object
[in] flags flags to be ORed to the flags mask
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 323 of file osal.c.
References event_source::cb, event_source::flags, and osalDbgCheck.
Referenced by canSleep(), canWakeup(), and osalEventBroadcastFlags().
osalEventBroadcastFlags()
void osalEventBroadcastFlags (event_source_t * esp, eventflags_t flags)
Add flags to an event source object.
Parameters
[in] esp pointer to the event flags object
[in] flags flags to be ORed to the flags mask
Function Class:^^This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 341 of file osal.c.
References osalDbgCheck, osalEventBroadcastFlagsI(), osalSysLock(), and osalSysUnlock().
osalEventSetCallback()
void osalEventSetCallback (event_source_t * esp, eventcallback_t cb, void * param)
Event callback setup.
Note
The callback is invoked from ISR context and can only invoke I-Class functions. The callback is meant to wakeup the task that will handle the event by calling osalEventGetAndClearFlagsI().
This function is not part of the OSAL API and is provided exclusively as an example and for convenience.
Parameters
[in] esp pointer to the event flags object
[in] cb pointer to the callback function
[in] param parameter to be passed to the callback function
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 365 of file osal.c.
References event_source::cb, osalDbgCheck, and event_source::param.
osalMutexLock()
void osalMutexLock (mutex_t * mp)
Locks the specified mutex.
Postcondition
The mutex is locked and inserted in the per-thread stack of owned mutexes.
Parameters
[in,out] mp pointer to the mutex_t object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 384 of file osal.c.
References osalDbgCheck.
Referenced by adcAcquireBus(), dacAcquireBus(), eflAcquireBus(), i2cAcquireBus(), uartAcquireBus(), and wspiAcquireBus().
osalMutexUnlock()
void osalMutexUnlock (mutex_t * mp)
Unlocks the specified mutex.
Note
The HAL guarantees to release mutex in reverse lock order. The mutex being unlocked is guaranteed to be the last locked mutex by the invoking thread. The implementation can rely on this behavior and eventually ignore the mp parameter which is supplied in order to support those OSes not supporting a stack of the owned mutexes.
Parameters
[in,out] mp pointer to the mutex_t object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 404 of file osal.c.
References osalDbgCheck.
Referenced by adcReleaseBus(), dacReleaseBus(), eflReleaseBus(), i2cReleaseBus(), uartReleaseBus(), and wspiReleaseBus().
osalSysDisable()
static void osalSysDisable (void) inline static
Disables interrupts globally.
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 582 of file osal.h.
Referenced by osalSysHalt().
osalSysEnable()
static void osalSysEnable (void) inline static
Enables interrupts globally.
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 591 of file osal.h.
osalSysLock()
static void osalSysLock (void) inline static
Enters a critical zone from thread context.
Note
This function cannot be used for reentrant critical zones.
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 601 of file osal.h.
Referenced by adcConvert(), adcStart(), adcStartConversion(), adcStop(), adcStopConversion(), canReceiveTimeout(), canSleep(), canStart(), canStop(), canTransmitTimeout(), canWakeup(), cryStart(), cryStop(), dacConvert(), dacStart(), dacStartConversion(), dacStop(), dacStopConversion(), eflStart(), eflStop(), gptChangeInterval(), gptStart(), gptStartContinuous(), gptStartOneShot(), gptStop(), gptStopTimer(), i2cStart(), i2cStop(), i2sStart(), i2sStartExchange(), i2sStop(), i2sStopExchange(), ibqGetFullBufferTimeout(), ibqGetTimeout(), ibqReadTimeout(), ibqReleaseEmptyBuffer(), icuDisableNotifications(), icuEnableNotifications(), icuStart(), icuStartCapture(), icuStop(), icuStopCapture(), icuWaitCapture(), iqGetTimeout(), iqReadTimeout(), macStart(), macStop(), macWaitReceiveDescriptor(), macWaitTransmitDescriptor(), mmcDisconnect(), obqFlush(), obqGetEmptyBufferTimeout(), obqPostFullBuffer(), obqPutTimeout(), obqWriteTimeout(), oqPutTimeout(), oqWriteTimeout(), osalEventBroadcastFlags(), palWaitLineTimeout(), palWaitPadTimeout(), pwmChangePeriod(), pwmDisableChannel(), pwmDisableChannelNotification(), pwmDisablePeriodicNotification(), pwmEnableChannel(), pwmEnableChannelNotification(), pwmEnablePeriodicNotification(), pwmStart(), pwmStop(), sdcDisconnect(), sdcGetAndClearErrors(), sdcStart(), sdcStop(), sdGetWouldBlock(), sdPutWouldBlock(), sdStart(), sdStop(), sduStart(), sduStop(), sioAsyncRead(), sioAsyncWrite(), sioGetAndClearEvents(), sioStart(), sioStartOperation(), sioStop(), sioStopOperation(), sioSynchronizeTXEnd(), trngStart(), trngStop(), uartReceiveTimeout(), uartSendFullTimeout(), uartSendTimeout(), uartStart(), uartStartReceive(), uartStartSend(), uartStop(), uartStopReceive(), uartStopSend(), usbReceive(), usbStart(), usbStop(), usbTransmit(), wdgReset(), wdgStart(), wdgStop(), wspiStart(), wspiStartCommand(), wspiStartReceive(), wspiStartSend(), wspiStop(), and wspiUnmapFlash().
osalSysUnlock()
static void osalSysUnlock (void) inline static
Leaves a critical zone from thread context.
Note
This function cannot be used for reentrant critical zones.
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 611 of file osal.h.
Referenced by adcConvert(), adcStartConversion(), adcStop(), adcStopConversion(), canSleep(), canWakeup(), cryStop(), dacConvert(), dacStartConversion(), dacStop(), dacStopConversion(), gptChangeInterval(), gptStartContinuous(), gptStartOneShot(), gptStop(), gptStopTimer(), i2cStop(), i2sStartExchange(), i2sStop(), i2sStopExchange(), ibqGetFullBufferTimeout(), ibqReleaseEmptyBuffer(), icuDisableNotifications(), icuEnableNotifications(), icuStartCapture(), icuStop(), icuStopCapture(), icuWaitCapture(), macStop(), mmcDisconnect(), obqFlush(), obqGetEmptyBufferTimeout(), obqPostFullBuffer(), osalEventBroadcastFlags(), palWaitLineTimeout(), palWaitPadTimeout(), pwmChangePeriod(), pwmDisableChannel(), pwmDisableChannelNotification(), pwmDisablePeriodicNotification(), pwmEnableChannel(), pwmEnableChannelNotification(), pwmEnablePeriodicNotification(), pwmStop(), sdcDisconnect(), sdcStop(), sdGetWouldBlock(), sdPutWouldBlock(), sdStop(), sduStart(), sduStop(), sioAsyncRead(), sioAsyncWrite(), sioGetAndClearEvents(), sioStop(), trngStop(), uartStartReceive(), uartStartSend(), uartStop(), usbReceive(), usbTransmit(), wdgReset(), wdgStop(), wspiStartCommand(), wspiStartReceive(), wspiStartSend(), wspiStop(), and wspiUnmapFlash().
osalSysLockFromISR()
static void osalSysLockFromISR (void) inline static
Enters a critical zone from ISR context.
Note
This function cannot be used for reentrant critical zones.
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 621 of file osal.h.
Referenced by _usb_ep0out(), _usb_reset(), _usb_suspend(), sduDataReceived(), and sduDataTransmitted().
osalSysUnlockFromISR()
static void osalSysUnlockFromISR (void) inline static
Leaves a critical zone from ISR context.
Note
This function cannot be used for reentrant critical zones.
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 631 of file osal.h.
Referenced by _usb_ep0out(), and sduDataTransmitted().
osalSysGetStatusAndLockX()
static syssts_t osalSysGetStatusAndLockX (void) inline static
Returns the execution status and enters a critical zone.
This functions enters into a critical zone and can be called from any context. Because its flexibility it is less efficient than chSysLock() which is preferable when the calling context is known.
Postcondition
The system is in a critical zone.
Returns
The previous system status, the encoding of this status word is architecture-dependent and opaque.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 648 of file osal.h.
osalSysRestoreStatusX()
static void osalSysRestoreStatusX (syssts_t sts) inline static
Restores the specified execution status and leaves a critical zone.
Note
A call to chSchRescheduleS() is automatically performed if exiting the critical zone and if not in ISR context.
Parameters
[in] sts the system status to be restored.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 662 of file osal.h.
osalTimeAddX()
static systime_t osalTimeAddX (systime_t systime, sysinterval_t interval) inline static
Adds an interval to a system time returning a system time.
Parameters
[in] systime base system time
[in] interval interval to be added
Returns
The new system time.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 676 of file osal.h.
osalTimeDiffX()
static sysinterval_t osalTimeDiffX (systime_t start, systime_t end) inline static
Subtracts two system times returning an interval.
Parameters
[in] start first system time
[in] end second system time
Returns
The interval representing the time difference.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 691 of file osal.h.
osalTimeIsInRangeX()
static bool osalTimeIsInRangeX (systime_t time, systime_t start, systime_t end) inline static
Checks if the specified time is within the specified time window.
Note
When start==end then the function returns always false because the time window has zero size.
This function can be called from any context.
Parameters
[in] time the time to be verified
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values
true current time within the specified time window.
false current time not within the specified time window.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 710 of file osal.h.
osalThreadQueueObjectInit()
static void osalThreadQueueObjectInit (threads_queue_t * tqp) inline static
Initializes a threads queue object.
Parameters
[out] tqp pointer to the threads queue object
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 725 of file osal.h.
References osalDbgCheck.
Referenced by canObjectInit(), ibqObjectInit(), iqObjectInit(), macObjectInit(), obqObjectInit(), and oqObjectInit().
osalEventObjectInit()
static void osalEventObjectInit (event_source_t * esp) inline static
Initializes an event source object.
Parameters
[out] esp pointer to the event source object
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 737 of file osal.h.
References event_source::cb, event_source::flags, osalDbgCheck, and event_source::param.
Referenced by canObjectInit(), and macObjectInit().
osalMutexObjectInit()
static void osalMutexObjectInit (mutex_t * mp) inline static
Initializes s mutex_t object.
Parameters
[out] mp pointer to the mutex_t object
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 753 of file osal.h.
References osalDbgCheck.
Referenced by adcObjectInit(), dacObjectInit(), i2cObjectInit(), uartObjectInit(), and wspiObjectInit().
Variable Documentation
osal_halt_msg [1/2]
const char* osal_halt_msg
Pointer to a halt error message.
Note
The message is meant to be retrieved by the debugger after the system halt caused by an unexpected error.
Definition at line 40 of file osal.c.
Referenced by osalSysHalt().
osal_halt_msg [2/2]
const char* osal_halt_msg
Pointer to a halt error message.
Note
The message is meant to be retrieved by the debugger after the system halt caused by an unexpected error.
Definition at line 40 of file osal.c.
Referenced by osalSysHalt().