ChibiOS/HAL: ST Driver
ST Driver
HAL » Normal Drivers
Generic System Tick Driver.
Detailed Description
Generic System Tick Driver.
This module implements a system tick timer in order to support the underlying operating system.
Functions
void stInit (void)
ST Driver initialization.
void stBind (void)
Enables an alarm interrupt on the invoking core.
systime_t stGetCounter (void)
Returns the time counter value.
void stStartAlarm (systime_t abstime)
Starts the alarm zero.
void stStopAlarm (void)
Stops the alarm zero interrupt.
void stSetAlarm (systime_t abstime)
Sets the alarm zero time.
systime_t stGetAlarm (void)
Returns the alarm zero current time.
bool stIsAlarmActive (void)
Determines if the alarm zero is active.
void stSetCallback (unsigned alarm, st_callback_t cb)
Associates a callback to an alarm.
void stBindAlarmN (unsigned alarm)
Enables an alarm interrupt on the invoking core.
void stStartAlarmN (unsigned alarm, systime_t abstime)
Starts an additional alarm.
void stStopAlarmN (unsigned alarm)
Stops an additional alarm.
void stSetAlarmN (unsigned alarm, systime_t abstime)
Sets an additional alarm time.
systime_t stGetAlarmN (unsigned alarm)
Returns an additional alarm current time.
bool stIsAlarmActiveN (unsigned alarm)
Determines if the specified alarm is active.
void st_lld_init (void)
Low level ST driver initialization.
static systime_t st_lld_get_counter (void)
Returns the time counter value.
static void st_lld_start_alarm (systime_t abstime)
Starts the alarm.
static void st_lld_stop_alarm (void)
Stops the alarm interrupt.
static void st_lld_set_alarm (systime_t abstime)
Sets the alarm time.
static systime_t st_lld_get_alarm (void)
Returns the current alarm time.
static bool st_lld_is_alarm_active (void)
Determines if the alarm is active.
Variables
st_callback_t st_callbacks [ST_LLD_NUM_ALARMS]
Callback pointers for each alarm.
Function Documentation
stInit()
void stInit (void)
ST Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 69 of file hal_st.c.
stBind()
void stBind (void)
Enables an alarm interrupt on the invoking core.
Note
Must be called before any other alarm-related function.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 87 of file hal_st.c.
stGetCounter()
systime_t stGetCounter (void)
Returns the time counter value.
Note
This functionality is only available in free running mode, the behaviour in periodic mode is undefined.
Returns
The counter value.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 103 of file hal_st.c.
References st_lld_get_counter().
stStartAlarm()
void stStartAlarm (systime_t abstime)
Starts the alarm zero.
Note
Makes sure that no spurious alarms are triggered after this call.
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] abstime the time to be set for the first alarm
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 119 of file hal_st.c.
References osalDbgAssert, st_lld_start_alarm(), and stIsAlarmActive().
stStopAlarm()
void stStopAlarm (void)
Stops the alarm zero interrupt.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 133 of file hal_st.c.
References st_lld_stop_alarm().
stSetAlarm()
void stSetAlarm (systime_t abstime)
Sets the alarm zero time.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] abstime the time to be set for the next alarm
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 147 of file hal_st.c.
References osalDbgAssert, st_lld_set_alarm(), and stIsAlarmActive().
stGetAlarm()
systime_t stGetAlarm (void)
Returns the alarm zero current time.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Returns
The currently set alarm time.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 163 of file hal_st.c.
References osalDbgAssert, st_lld_get_alarm(), and stIsAlarmActive().
stIsAlarmActive()
bool stIsAlarmActive (void)
Determines if the alarm zero is active.
Returns
The alarm status.
Return values
false if the alarm is not active.
true is the alarm is active
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 179 of file hal_st.c.
References st_lld_is_alarm_active().
Referenced by stGetAlarm(), stSetAlarm(), and stStartAlarm().
stSetCallback()
void stSetCallback (unsigned alarm, st_callback_t cb)
Associates a callback to an alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
[in] cb alarm callback or NULL
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 197 of file hal_st.c.
stBindAlarmN()
void stBindAlarmN (unsigned alarm)
Enables an alarm interrupt on the invoking core.
Note
Must be called before any other alarm-related function.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 213 of file hal_st.c.
References osalDbgCheck.
stStartAlarmN()
void stStartAlarmN (unsigned alarm, systime_t abstime)
Starts an additional alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
[in] abstime the time to be set for the first alarm
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 234 of file hal_st.c.
References osalDbgCheck.
stStopAlarmN()
void stStopAlarmN (unsigned alarm)
Stops an additional alarm.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 251 of file hal_st.c.
References osalDbgCheck.
stSetAlarmN()
void stSetAlarmN (unsigned alarm, systime_t abstime)
Sets an additional alarm time.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
[in] abstime the time to be set for the next alarm
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 268 of file hal_st.c.
References osalDbgCheck.
stGetAlarmN()
systime_t stGetAlarmN (unsigned alarm)
Returns an additional alarm current time.
Note
This functionality is only available in free running mode, the behavior in periodic mode is undefined.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
Returns
The currently set alarm time.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 286 of file hal_st.c.
References osalDbgCheck.
stIsAlarmActiveN()
bool stIsAlarmActiveN (unsigned alarm)
Determines if the specified alarm is active.
Parameters
[in] alarm alarm channel number (0..ST_LLD_NUM_ALARMS-1)
Returns
The alarm status.
Return values
false if the alarm is not active.
true is the alarm is active
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 304 of file hal_st.c.
References osalDbgCheck.
st_lld_init()
void st_lld_init (void)
Low level ST driver initialization.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 62 of file hal_st_lld.c.
st_lld_get_counter()
static systime_t st_lld_get_counter (void) inline static
Returns the time counter value.
Returns
The counter value.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 73 of file hal_st_lld.h.
Referenced by stGetCounter().
st_lld_start_alarm()
static void st_lld_start_alarm (systime_t abstime) inline static
Starts the alarm.
Note
Makes sure that no spurious alarms are triggered after this call.
Parameters
[in] abstime the time to be set for the first alarm
Function Class:^^Not an API, this function is for internal use only.
Definition at line 87 of file hal_st_lld.h.
Referenced by stStartAlarm().
st_lld_stop_alarm()
static void st_lld_stop_alarm (void) inline static
Stops the alarm interrupt.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 97 of file hal_st_lld.h.
Referenced by stStopAlarm().
st_lld_set_alarm()
static void st_lld_set_alarm (systime_t abstime) inline static
Sets the alarm time.
Parameters
[in] abstime the time to be set for the next alarm
Function Class:^^Not an API, this function is for internal use only.
Definition at line 108 of file hal_st_lld.h.
Referenced by stSetAlarm().
st_lld_get_alarm()
static systime_t st_lld_get_alarm (void) inline static
Returns the current alarm time.
Returns
The currently set alarm time.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 120 of file hal_st_lld.h.
Referenced by stGetAlarm().
st_lld_is_alarm_active()
static bool st_lld_is_alarm_active (void) inline static
Determines if the alarm is active.
Returns
The alarm status.
Return values
false if the alarm is not active.
true is the alarm is active
Function Class:^^Not an API, this function is for internal use only.
Definition at line 134 of file hal_st_lld.h.
Referenced by stIsAlarmActive().
Variable Documentation
st_callbacks
st_callback_t st_callbacks[ST_LLD_NUM_ALARMS]
Callback pointers for each alarm.
Note
If some alarms have static callbacks defined in the LLD then some of the pointers might be unused (never called through).
Definition at line 51 of file hal_st.c.