ChibiOS/HAL: Input Formatter Utility
Input Formatter Utility
HAL » Interfaces and Classes » Streams
Detailed Description
Mini scanf-like functionality.
Macros
#define CHSCANF_USE_FLOAT FALSE
Float type support.
Functions
int chvscanf (BaseBufferedStream *chp, const char *fmt, va_list ap)
System formatted input function.
int chscanf (BaseBufferedStream *chp, const char *fmt,...)
System formatted input function.
int chsnscanf (char *str, size_t size, const char *fmt,...)
System formatted input function.
int chvsnscanf (char *str, size_t size, const char *fmt, va_list ap)
System formatted input function.
Macro Definition Documentation
CHSCANF_USE_FLOAT
#define CHSCANF_USE_FLOAT FALSE
Float type support.
Definition at line 40 of file chscanf.h.
Function Documentation
chvscanf()
int chvscanf (BaseBufferedStream * chp, const char * fmt, va_list ap)
System formatted input function.
This function implements a minimal vscanf()-like functionality with input on a BaseSequentialStream. The general parameters format is: %[*][width][l|L]p The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] chp pointer to a BufferedStream implementing object
[in] fmt formatting string
[in] ap list of parameters
Returns
The number parameters in ap that have been successfully filled. This does not conform to the standard in that if a failure (either matching or input) occurs before any parameters are assigned, the function will return 0.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 111 of file chscanf.c.
References streamGet.
Referenced by chscanf(), and chvsnscanf().
chscanf()
int chscanf (BaseBufferedStream * chp, const char * fmt, ...)
System formatted input function.
This function implements a minimal scanf() like functionality with input from a BufferedStream. The general parameters format is: %[*][width][l|L]p The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] chp pointer to a BufferedStream implementing object
[in] fmt formatting string
Returns
The number parameters in ap that have been successfully filled. This does not conform to the standard in that if a failure (either matching or input) occurs before any parameters are assigned, the function will return 0.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 695 of file chscanf.c.
References chvscanf().
chsnscanf()
int chsnscanf (char * str, size_t size, const char * fmt, ...)
System formatted input function.
This function implements a minimal snscanf()-like functionality. The general parameters format is: %[*][width][l|L]p The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] str pointer to a buffer
[in] size size of the buffer
[in] fmt formatting string
Returns
The number parameters in ap that have been successfully filled. This does not conform to the standard in that if a failure (either matching or input) occurs before any parameters are assigned, the function will return 0.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 734 of file chscanf.c.
References chvsnscanf().
chvsnscanf()
int chvsnscanf (char * str, size_t size, const char * fmt, va_list ap)
System formatted input function.
This function implements a minimal vsnscanf()-like functionality. The general parameters format is: %[*][width][l|L]p The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] str pointer to a buffer
[in] size size of the buffer
[in] fmt formatting string
[in] ap list of parameters
Returns
The number parameters in ap that have been successfully filled. This does not conform to the standard in that if a failure (either matching or input) occurs before any parameters are assigned, the function will return 0.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 776 of file chscanf.c.
References chvscanf(), and msObjectInit().
Referenced by chsnscanf().