ChibiOS/HAL: Serial NOR Flash Driver
Serial NOR Flash Driver
HAL » Complex Drivers
Serial NOR Flash driver.
Detailed Description
Serial NOR Flash driver.
This module implements a generic driver for serial NOR Flash devices.
Driver State Machine
The flash driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
Macros
#define _snor_flash_methods_alone
SNORDriver specific methods.
#define _snor_flash_methods
SNORDriver specific methods with inherited ones.
Bus interface modes.
#define SNOR_BUS_DRIVER_SPI 0U
#define SNOR_BUS_DRIVER_WSPI 1U
Configuration options
#define SNOR_BUS_DRIVER SNOR_BUS_DRIVER_WSPI
Physical transport interface.
#define SNOR_SHARED_BUS TRUE
Shared bus switch.
Data Structures
struct SNORConfig
Type of a SNOR configuration structure.
struct SNORDriverVMT
SNOR virtual methods table.
struct SNORDriver
Type of SNOR flash class.
Functions
static const flash_descriptor_t * snor_get_descriptor (void *instance)
Returns a pointer to the device descriptor.
void bus_acquire (BUSDriver *busp, const BUSConfig *config)
Bus acquisition and lock.
void bus_release (BUSDriver *busp)
Bus release.
void bus_stop (BUSDriver *busp)
Stops the underlying bus driver.
void bus_cmd (BUSDriver *busp, uint32_t cmd)
Sends a naked command.
void bus_cmd_send (BUSDriver *busp, uint32_t cmd, size_t n, const uint8_t *p)
Sends a command followed by a data transmit phase.
void bus_cmd_receive (BUSDriver *busp, uint32_t cmd, size_t n, uint8_t *p)
Sends a command followed by a data receive phase.
void bus_cmd_addr (BUSDriver *busp, uint32_t cmd, flash_offset_t offset)
Sends a command followed by a flash address.
void bus_cmd_addr_send (BUSDriver *busp, uint32_t cmd, flash_offset_t offset, size_t n, const uint8_t *p)
Sends a command followed by a flash address and a data transmit phase.
void bus_cmd_addr_receive (BUSDriver *busp, uint32_t cmd, flash_offset_t offset, size_t n, uint8_t *p)
Sends a command followed by a flash address and a data receive phase.
void bus_cmd_dummy_receive (BUSDriver *busp, uint32_t cmd, uint32_t dummy, size_t n, uint8_t *p)
Sends a command followed by dummy cycles and a data receive phase.
void bus_cmd_addr_dummy_receive (BUSDriver *busp, uint32_t cmd, flash_offset_t offset, uint32_t dummy, size_t n, uint8_t *p)
Sends a command followed by a flash address, dummy cycles and a data receive phase.
void snorObjectInit (SNORDriver *devp)
Initializes an instance.
void snorStart (SNORDriver *devp, const SNORConfig *config)
Configures and activates SNOR driver.
void snorStop (SNORDriver *devp)
Deactivates the SNOR driver.
void snorMemoryMap (SNORDriver *devp, uint8_t **addrp)
Enters the memory Mapping mode.
void snorMemoryUnmap (SNORDriver *devp)
Leaves the memory Mapping mode.
Variables
static const struct SNORDriverVMT snor_vmt
Virtual methods table.
Macro Definition Documentation
SNOR_BUS_DRIVER
#define SNOR_BUS_DRIVER SNOR_BUS_DRIVER_WSPI
Physical transport interface.
Definition at line 54 of file hal_serial_nor.h.
SNOR_SHARED_BUS
#define SNOR_SHARED_BUS TRUE
Shared bus switch.
If set to TRUE the device acquires bus ownership on each transaction.
Note
Requires SPI_USE_MUTUAL_EXCLUSION or WSPI_USE_MUTUAL_EXCLUSION depending on mode selected with SNOR_BUS_MODE.
Definition at line 66 of file hal_serial_nor.h.
_snor_flash_methods_alone
#define _snor_flash_methods_alone
Value:
/* Read SFDP.*/                                                           \
  flash_error_t (*read_sfdp)(void *instance,                                \
                 flash_offset_t offset,                                     \
                 size_t n,                                                  \
                 uint8_t *rp);
SNORDriver specific methods.
Definition at line 99 of file hal_serial_nor.h.
_snor_flash_methods
#define _snor_flash_methods
Value:
_base_flash_methods                                                       \
  _snor_flash_methods_alone
SNORDriver specific methods with inherited ones.
Definition at line 109 of file hal_serial_nor.h.
Function Documentation
snor_get_descriptor()
static const flash_descriptor_t * snor_get_descriptor (void * instance) static
Returns a pointer to the device descriptor.
Parameters
[in] instance instance pointer
Returns
Pointer to a static descriptor structure.
Definition at line 75 of file hal_serial_nor.c.
References osalDbgAssert, and osalDbgCheck.
bus_acquire()
void bus_acquire (BUSDriver * busp, const BUSConfig * config)
Bus acquisition and lock.
Parameters
[in] busp pointer to the bus driver
[in] config bus configuration
Function Class:^^Not an API, this function is for internal use only.
Definition at line 318 of file hal_serial_nor.c.
Referenced by snorMemoryMap(), and snorMemoryUnmap().
bus_release()
void bus_release (BUSDriver * busp)
Bus release.
Parameters
[in] busp pointer to the bus driver
Function Class:^^Not an API, this function is for internal use only.
Definition at line 335 of file hal_serial_nor.c.
Referenced by snorMemoryMap(), and snorMemoryUnmap().
bus_stop()
void bus_stop (BUSDriver * busp)
Stops the underlying bus driver.
Parameters
[in] busp pointer to the bus driver
Function Class:^^Not an API, this function is for internal use only.
Definition at line 364 of file hal_serial_nor.c.
bus_cmd()
void bus_cmd (BUSDriver * busp, uint32_t cmd)
Sends a naked command.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
Function Class:^^Not an API, this function is for internal use only.
Definition at line 381 of file hal_serial_nor.c.
bus_cmd_send()
void bus_cmd_send (BUSDriver * busp, uint32_t cmd, size_t n, const uint8_t * p)
Sends a command followed by a data transmit phase.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] n number of bytes to receive
[in] p data buffer
Function Class:^^Not an API, this function is for internal use only.
Definition at line 411 of file hal_serial_nor.c.
bus_cmd_receive()
void bus_cmd_receive (BUSDriver * busp, uint32_t cmd, size_t n, uint8_t * p)
Sends a command followed by a data receive phase.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] n number of bytes to receive
[out] p data buffer
Function Class:^^Not an API, this function is for internal use only.
Definition at line 442 of file hal_serial_nor.c.
bus_cmd_addr()
void bus_cmd_addr (BUSDriver * busp, uint32_t cmd, flash_offset_t offset)
Sends a command followed by a flash address.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] offset flash offset
Function Class:^^Not an API, this function is for internal use only.
Definition at line 475 of file hal_serial_nor.c.
bus_cmd_addr_send()
void bus_cmd_addr_send (BUSDriver * busp, uint32_t cmd, flash_offset_t offset, size_t n, const uint8_t * p)
Sends a command followed by a flash address and a data transmit phase.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] offset flash offset
[in] n number of bytes to receive
[in] p data buffer
Function Class:^^Not an API, this function is for internal use only.
Definition at line 510 of file hal_serial_nor.c.
bus_cmd_addr_receive()
void bus_cmd_addr_receive (BUSDriver * busp, uint32_t cmd, flash_offset_t offset, size_t n, uint8_t * p)
Sends a command followed by a flash address and a data receive phase.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] offset flash offset
[in] n number of bytes to receive
[out] p data buffer
Function Class:^^Not an API, this function is for internal use only.
Definition at line 550 of file hal_serial_nor.c.
bus_cmd_dummy_receive()
void bus_cmd_dummy_receive (BUSDriver * busp, uint32_t cmd, uint32_t dummy, size_t n, uint8_t * p)
Sends a command followed by dummy cycles and a data receive phase.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] dummy number of dummy cycles
[in] n number of bytes to receive
[out] p data buffer
Function Class:^^Not an API, this function is for internal use only.
Definition at line 591 of file hal_serial_nor.c.
bus_cmd_addr_dummy_receive()
void bus_cmd_addr_dummy_receive (BUSDriver * busp, uint32_t cmd, flash_offset_t offset, uint32_t dummy, size_t n, uint8_t * p)
Sends a command followed by a flash address, dummy cycles and a data receive phase.
Parameters
[in] busp pointer to the bus driver
[in] cmd instruction code
[in] offset flash offset
[in] dummy number of dummy cycles
[in] n number of bytes to receive
[out] p data buffer
Function Class:^^Not an API, this function is for internal use only.
Definition at line 619 of file hal_serial_nor.c.
snorObjectInit()
void snorObjectInit (SNORDriver * devp)
Initializes an instance.
Parameters
[out] devp pointer to the SNORDriver object
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 643 of file hal_serial_nor.c.
References osalDbgCheck, snor_vmt, and SNORDriver::vmt.
snorStart()
void snorStart (SNORDriver * devp, const SNORConfig * config)
Configures and activates SNOR driver.
Parameters
[in] devp pointer to the SNORDriver object
[in] config pointer to the configuration
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 660 of file hal_serial_nor.c.
References osalDbgAssert, and osalDbgCheck.
snorStop()
void snorStop (SNORDriver * devp)
Deactivates the SNOR driver.
Parameters
[in] devp pointer to the SNORDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 690 of file hal_serial_nor.c.
References osalDbgAssert, and osalDbgCheck.
snorMemoryMap()
void snorMemoryMap (SNORDriver * devp, uint8_t ** addrp)
Enters the memory Mapping mode.
The memory mapping mode is only available when the WSPI mode is selected and the underlying WSPI controller supports the feature.
Parameters
[in] devp pointer to the SNORDriver object
[out] addrp pointer to the memory start address of the mapped flash or NULL
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 728 of file hal_serial_nor.c.
References bus_acquire(), bus_release(), SNORDriver::config, and wspiMapFlash().
snorMemoryUnmap()
void snorMemoryUnmap (SNORDriver * devp)
Leaves the memory Mapping mode.
Parameters
[in] devp pointer to the SNORDriver object
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 752 of file hal_serial_nor.c.
References bus_acquire(), bus_release(), SNORDriver::config, and wspiUnmapFlash().
Variable Documentation
snor_vmt
const struct SNORDriverVMT snor_vmt static
Initial value:
= {
  (size_t)0,
  snor_get_descriptor, snor_read, snor_program,
  snor_start_erase_all, snor_start_erase_sector,
  snor_query_erase, snor_verify_erase,
  snor_read_sfdp
}
Virtual methods table.
Definition at line 57 of file hal_serial_nor.c.
Referenced by snorObjectInit().