ChibiOS/HAL: HAL Driver
HAL Driver
HAL » Normal Drivers
Hardware Abstraction Layer.
Detailed Description
Hardware Abstraction Layer.
The HAL (Hardware Abstraction Layer) driver performs the system initialization and includes the platform support code shared by the other drivers. This driver does contain any API function except for a general initialization function halInit() that must be invoked before any HAL service can be used, usually the HAL initialization should be performed immediately before the kernel initialization.
Some HAL driver implementations also offer a custom early clock setup function that can be invoked before the C runtime initialization in order to accelerate the startup time.
Macros
#define __CHIBIOS_HAL__
ChibiOS/HAL identification macro.
#define CH_HAL_STABLE 1
Stable release flag.
#define HAL_LLD_SELECT_SPI_V2 TRUE
Requires use of SPIv2 driver model.
#define HAL_LLD_USE_CLOCK_MANAGEMENT
Specifies implementation of dynamic clock management.
ChibiOS/HAL version identification
#define CH_HAL_VERSION "8.2.0"
HAL version string.
#define CH_HAL_MAJOR 8
HAL version major number.
#define CH_HAL_MINOR 2
HAL version minor number.
#define CH_HAL_PATCH 0
HAL version patch number.
Return codes
#define HAL_SUCCESS false
HAL operation success.
#define HAL_FAILED true
HAL operation failed.
Return codes for HAL functions
#define HAL_RET_SUCCESS MSG_OK
#define HAL_RET_CONFIG_ERROR (msg_t)-16
Configuration error.
#define HAL_RET_NO_RESOURCE (msg_t)-17
A required resource is not available.
#define HAL_RET_HW_BUSY (msg_t)-18
The peripheral is busy.
#define HAL_RET_HW_FAILURE (msg_t)-19
Peripheral failure.
Platform identification macros
#define PLATFORM_NAME "templates"
Typedefs
typedef unsigned halclkpt_t
Type of a clock point identifier.
typedef uint32_t halfreq_t
Type of a clock point frequency in Hz.
Data Structures
struct halclkcfg_t
Type of a clock configuration structure.
Functions
void halInit (void)
HAL initialization.
static bool halClockSwitchMode (const halclkcfg_t *ccp)
Switches to a different clock configuration.
static halfreq_t halClockGetPointX (halclkpt_t clkpt)
Returns the frequency of a clock point in Hz.
void hal_lld_init (void)
Low level HAL driver initialization.
bool hal_lld_clock_switch_mode (const halclkcfg_t *ccp)
Switches to a different clock configuration.
halfreq_t hal_lld_get_clock_point (halclkpt_t clkpt)
Returns the frequency of a clock point in Hz.
Macro Definition Documentation
__CHIBIOS_HAL__
#define __CHIBIOS_HAL__
ChibiOS/HAL identification macro.
Definition at line 39 of file hal.h.
CH_HAL_STABLE
#define CH_HAL_STABLE 1
Stable release flag.
Definition at line 44 of file hal.h.
CH_HAL_VERSION
#define CH_HAL_VERSION "8.2.0"
HAL version string.
Definition at line 53 of file hal.h.
CH_HAL_MAJOR
#define CH_HAL_MAJOR 8
HAL version major number.
Definition at line 58 of file hal.h.
CH_HAL_MINOR
#define CH_HAL_MINOR 2
HAL version minor number.
Definition at line 63 of file hal.h.
CH_HAL_PATCH
#define CH_HAL_PATCH 0
HAL version patch number.
Definition at line 68 of file hal.h.
HAL_SUCCESS
#define HAL_SUCCESS false
HAL operation success.
Deprecated:
Definition at line 79 of file hal.h.
Referenced by mmcDisconnect(), mmcGetInfo(), sdc_cmd6_check_status(), sdc_lld_read(), sdc_lld_send_cmd_long_crc(), sdc_lld_send_cmd_short(), sdc_lld_send_cmd_short_crc(), sdc_lld_sync(), sdc_lld_write(), sdcDisconnect(), and sdcGetInfo().
HAL_FAILED
#define HAL_FAILED true
HAL operation failed.
Deprecated:
Definition at line 84 of file hal.h.
Referenced by mmcGetInfo(), mmcSequentialRead(), mmcSequentialWrite(), mmcStopSequentialWrite(), mmcSync(), sdc_cmd6_check_status(), sdcDisconnect(), sdcGetInfo(), and sdcSync().
HAL_RET_CONFIG_ERROR
#define HAL_RET_CONFIG_ERROR (msg_t)-16
Configuration error.
An error has been detected in the driver configuration structure.
Definition at line 96 of file hal.h.
HAL_RET_NO_RESOURCE
#define HAL_RET_NO_RESOURCE (msg_t)-17
A required resource is not available.
One of the resources required for driver operations is not available.
Definition at line 102 of file hal.h.
HAL_RET_HW_BUSY
#define HAL_RET_HW_BUSY (msg_t)-18
The peripheral is busy.
The peripheral is not available or taken by some other system actor.
Definition at line 108 of file hal.h.
HAL_RET_HW_FAILURE
#define HAL_RET_HW_FAILURE (msg_t)-19
Peripheral failure.
Peripheral failed, for example HW timeouts.
Definition at line 113 of file hal.h.
HAL_LLD_SELECT_SPI_V2
#define HAL_LLD_SELECT_SPI_V2 TRUE
Requires use of SPIv2 driver model.
Definition at line 35 of file hal_lld.h.
HAL_LLD_USE_CLOCK_MANAGEMENT
#define HAL_LLD_USE_CLOCK_MANAGEMENT
Specifies implementation of dynamic clock management.
Definition at line 40 of file hal_lld.h.
Typedef Documentation
halclkpt_t
typedef unsigned halclkpt_t
Type of a clock point identifier.
Definition at line 77 of file hal_lld.h.
halfreq_t
typedef uint32_t halfreq_t
Type of a clock point frequency in Hz.
Definition at line 83 of file hal_lld.h.
Function Documentation
halInit()
void halInit (void)
HAL initialization.
This function invokes the low level initialization code then initializes all the drivers enabled in the HAL. Finally the board-specific initialization is performed by invoking boardInit() (usually defined in board.c).
Function Class:^^Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal.c.
References adcInit(), canInit(), cryInit(), dacInit(), eflInit(), gptInit(), hal_lld_init(), i2cInit(), i2sInit(), icuInit(), macInit(), osalInit(), palInit, pwmInit(), sdcInit(), sdInit(), and sioInit().
halClockSwitchMode()
static bool halClockSwitchMode (const halclkcfg_t * ccp) inline static
Switches to a different clock configuration.
Parameters
[in] ccp pointer to clock a halclkcfg_t structure
Returns
The clock switch result.
Return values
false if the clock switch succeeded
true if the clock switch failed
Function Class:^^Special function, this function has special requirements see the notes.
Definition at line 260 of file hal.h.
References hal_lld_clock_switch_mode().
halClockGetPointX()
static halfreq_t halClockGetPointX (halclkpt_t clkpt) inline static
Returns the frequency of a clock point in Hz.
Parameters
[in] clkpt clock point to be returned
Returns
The clock point frequency in Hz or zero if the frequency is unknown.
Function Class:^^This is an X-Class API, this function can be invoked from any context.
Definition at line 274 of file hal.h.
References hal_lld_get_clock_point().
hal_lld_init()
void hal_lld_init (void)
Low level HAL driver initialization.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 72 of file hal_lld.c.
Referenced by halInit().
hal_lld_clock_switch_mode()
bool hal_lld_clock_switch_mode (const halclkcfg_t * ccp)
Switches to a different clock configuration.
Parameters
[in] ccp pointer to clock a halclkcfg_t structure
Returns
The clock switch result.
Return values
false if the clock switch succeeded
true if the clock switch failed
Function Class:^^Not an API, this function is for internal use only.
Definition at line 87 of file hal_lld.c.
Referenced by halClockSwitchMode().
hal_lld_get_clock_point()
halfreq_t hal_lld_get_clock_point (halclkpt_t clkpt)
Returns the frequency of a clock point in Hz.
Parameters
[in] clkpt clock point to be returned
Returns
The clock point frequency in Hz or zero if the frequency is unknown.
Function Class:^^Not an API, this function is for internal use only.
Definition at line 103 of file hal_lld.c.
Referenced by halClockGetPointX().