ChibiOS/HAL: Output Formatter Utility
Output Formatter Utility
HAL » Interfaces and Classes » Streams
Detailed Description
Mini printf-like functionality.
Macros
#define CHPRINTF_USE_FLOAT FALSE
Float type support.
Functions
int chvprintf (BaseSequentialStream *chp, const char *fmt, va_list ap)
System formatted output function.
int chprintf (BaseSequentialStream *chp, const char *fmt,...)
System formatted output function.
int chsnprintf (char *str, size_t size, const char *fmt,...)
System formatted output function.
int chvsnprintf (char *str, size_t size, const char *fmt, va_list ap)
System formatted output function.
Macro Definition Documentation
CHPRINTF_USE_FLOAT
#define CHPRINTF_USE_FLOAT FALSE
Float type support.
Definition at line 34 of file chprintf.h.
Function Documentation
chvprintf()
int chvprintf (BaseSequentialStream * chp, const char * fmt, va_list ap)
System formatted output function.
This function implements a minimal vprintf()-like functionality with output on a BaseSequentialStream. The general parameters format is: %[-][width|*][.precision|*][l|L]p. The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] chp pointer to a BaseSequentialStream implementing object
[in] fmt formatting string
[in] ap list of parameters
Returns
The number of bytes that would have been written to chp if no stream error occurs
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 125 of file chprintf.c.
References streamPut.
Referenced by chprintf(), and chvsnprintf().
chprintf()
int chprintf (BaseSequentialStream * chp, const char * fmt, ...)
System formatted output function.
This function implements a minimal printf() like functionality with output on a BaseSequentialStream. The general parameters format is: %[-][width|*][.precision|*][l|L]p. The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] chp pointer to a BaseSequentialStream implementing object
[in] fmt formatting string
Returns
The number of bytes that would have been written to chp if no stream error occurs
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 366 of file chprintf.c.
References chvprintf().
chsnprintf()
int chsnprintf (char * str, size_t size, const char * fmt, ...)
System formatted output function.
This function implements a minimal snprintf()-like functionality. The general parameters format is: %[-][width|*][.precision|*][l|L]p. The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Postcondition
str is NUL-terminated, unless size is 0.
Parameters
[in] str pointer to a buffer
[in] size maximum size of the buffer
[in] fmt formatting string
Returns
The number of characters (excluding the terminating NUL byte) that would have been stored in str if there was room.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 404 of file chprintf.c.
References chvsnprintf().
chvsnprintf()
int chvsnprintf (char * str, size_t size, const char * fmt, va_list ap)
System formatted output function.
This function implements a minimal vsnprintf()-like functionality. The general parameters format is: %[-][width|*][.precision|*][l|L]p. The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Postcondition
str is NUL-terminated, unless size is 0.
Parameters
[in] str pointer to a buffer
[in] size maximum size of the buffer
[in] fmt formatting string
[in] ap list of parameters
Returns
The number of characters (excluding the terminating NUL byte) that would have been stored in str if there was room.
Function Class:^^Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 445 of file chprintf.c.
References chvprintf(), and msObjectInit().
Referenced by chsnprintf().